### ISSUE TITLE
Выход из аккаунта

### ISSUE THREAD

**Issue by ZhdanovPasha** [EricBorder/SkbSite#16]

**Comment by Dmi3Iva** [comment]
готово, если ты имел ввиду то, что имел ввиду 
![image](https://cloud.githubusercontent.com/assets/18259725/25760954/50d4c99a-31d9-11e7-8017-3a092b0ef8ec.png)

**Comment by ZhdanovPasha** [comment]
Почти.
Я имел ввиду функционал.
Сделано.
