### ISSUE TITLE
Добавить расширенную регистрацию

### ISSUE THREAD

**Issue by ZhdanovPasha** [EricBorder/SkbSite#19]
Добавить дополнительные параметры при регистрации пользователей(указание имени, фамилии, организации, роли). Сделать так, чтобы можно было просмотреть после регистрации(или входа на сайт, если уже зарегистрирован) можно было просмотреть данную информацию в личном кабинете

**Comment by Dmi3Iva** [comment]
Добавить пол, галочку на заказчика

**Comment by Dmi3Iva** [comment]
Осталось разобраться с ролями, перенесло в другой ишью.
