### ISSUE TITLE
Придумать, как зафиксировать footer

### ISSUE THREAD

**Issue by Dmi3Iva** [EricBorder/SkbSite#30]
![image](https://cloud.githubusercontent.com/assets/18259725/25979044/5af27a66-36c6-11e7-90ba-1285ed11fddc.png)

**Comment by Dmi3Iva** [comment]
Сейчас для футера установлен margin-top:80px, на всех страницах этого достаточно для корректного отображения, но вопрос открыт

**Comment by Dmi3Iva** [comment]
Заниматься этой хернёй это херня ©Павел

**Comment by Dmi3Iva** [comment]
Возможно допилить это с помощью js
screen.width. Определяет ширину экрана (монитора).
screen.height. Определяет высоту экрана (монитора).
document.body.clientWidth. Определяет ширину браузера.
document.body.clientHeight. Определяет высоту браузера.
$(window).width(). Определяет ширину браузера, но только при наличии jQuery.
$(window).height(). Определяет высоту браузера, но только при наличии jQuery.

**Comment by ZhdanovPasha** [comment]
С помощью метода Райана Фэйта данная задача успешно выполнена
