### ISSUE TITLE
Проблемы вёрстки

### ISSUE THREAD

**Issue by Dmi3Iva** [EricBorder/SkbSite#33]
Здесь выкладывают актуальные проблемы вёрстки сайта.

**Comment by EricBorder** [comment]
![image](https://cloud.githubusercontent.com/assets/18259725/26225750/14516ee2-3c29-11e7-8128-60927d4a9fea.png)

**Comment by EricBorder** [comment]
![image](https://cloud.githubusercontent.com/assets/18259725/26226207/4c6082b2-3c2b-11e7-863d-76733df4e517.png)

**Comment by EricBorder** [comment]
![image](https://cloud.githubusercontent.com/assets/18259725/26362424/2dad23b4-3fde-11e7-955b-c469a480a178.png)

**Comment by EricBorder** [comment]
![image](https://cloud.githubusercontent.com/assets/18259725/26450636/c18bcff6-4158-11e7-8d8d-1e27f15db149.png)

**Comment by Dmi3Iva** [comment]
Иссусы не помещаются на одну страницу, удаляю пустые. В этом вряд ли кто-то будет что-то добавлять
