### ISSUE TITLE
Сделать раздел "О нас"

### ISSUE THREAD

**Issue by ZhdanovPasha** [EricBorder/SkbSite#40]

**Comment by EricBorder** [comment]
# Осталось:
- нормальный текст и нормальные картинки

**Comment by EricBorder** [comment]
Нужно спросить у [Максима Царькова](https://vk.com/offreal)

**Comment by EricBorder** [comment]
Спросил

**Comment by Dmi3Iva** [comment]
Нормального ответа от скб нет. Предлагается сделать в бд отдельную сущность, а редактировать всё в редакторе, но в нём сейчас не работают картинки.
![image](https://user-images.githubusercontent.com/18259725/27126984-8d559900-50f9-11e7-952f-924ccda28be7.png)
