### ISSUE TITLE
Не работает изменение информации пользователя в личном кабинете

### ISSUE THREAD

**Issue by AntonDemchenko** [EricBorder/SkbSite#68]
Меняю организацию:
![default](https://user-images.githubusercontent.com/24816180/27453184-da0dd1de-5795-11e7-82ed-579ee04238a2.JPG)
Жму "Изменить", появляется окно:
![1](https://user-images.githubusercontent.com/24816180/27453241-0d975ec6-5796-11e7-9fe5-911fe71d122c.JPG)
Вроде изменение сохранилось, но при следующем заходе в личный кабинет поле "Организация" пустое:
![2](https://user-images.githubusercontent.com/24816180/27453263-1f8ab4b6-5796-11e7-9595-20c14745dd1b.JPG)

**Comment by ZhdanovPasha** [comment]
Это связано с изменением даты
Если изначально дата была не установлена, то произойдет ошибка, и все изменения не будут сохранены

**Comment by ZhdanovPasha** [comment]
Все изменения сохраняются, изменение даты обязательно
